//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungeons {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Images {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Images() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dungeons.Images", typeof(Images).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static System.Drawing.Bitmap arrow_north {
			get {
				object obj = ResourceManager.GetObject("arrow_north", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_scroll_east {
			get {
				object obj = ResourceManager.GetObject("arrow_scroll_east", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_scroll_north {
			get {
				object obj = ResourceManager.GetObject("arrow_scroll_north", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_scroll_reset {
			get {
				object obj = ResourceManager.GetObject("arrow_scroll_reset", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_scroll_south {
			get {
				object obj = ResourceManager.GetObject("arrow_scroll_south", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_scroll_west {
			get {
				object obj = ResourceManager.GetObject("arrow_scroll_west", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_turn_left {
			get {
				object obj = ResourceManager.GetObject("arrow_turn_left", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_turn_right {
			get {
				object obj = ResourceManager.GetObject("arrow_turn_right", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap baddie {
			get {
				object obj = ResourceManager.GetObject("baddie", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap baddie_lord {
			get {
				object obj = ResourceManager.GetObject("baddie_lord", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap combat_close {
			get {
				object obj = ResourceManager.GetObject("combat_close", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap combat_ranged {
			get {
				object obj = ResourceManager.GetObject("combat_ranged", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap damage {
			get {
				object obj = ResourceManager.GetObject("damage", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap damage_1 {
			get {
				object obj = ResourceManager.GetObject("damage_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap damage_2 {
			get {
				object obj = ResourceManager.GetObject("damage_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap damage_3 {
			get {
				object obj = ResourceManager.GetObject("damage_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap dead_baddie {
			get {
				object obj = ResourceManager.GetObject("dead_baddie", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_e_back {
			get {
				object obj = ResourceManager.GetObject("door_e_back", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_e_closed {
			get {
				object obj = ResourceManager.GetObject("door_e_closed", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_e_open {
			get {
				object obj = ResourceManager.GetObject("door_e_open", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_n_back {
			get {
				object obj = ResourceManager.GetObject("door_n_back", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_n_closed {
			get {
				object obj = ResourceManager.GetObject("door_n_closed", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_n_open {
			get {
				object obj = ResourceManager.GetObject("door_n_open", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_s_back {
			get {
				object obj = ResourceManager.GetObject("door_s_back", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_s_closed {
			get {
				object obj = ResourceManager.GetObject("door_s_closed", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_s_open {
			get {
				object obj = ResourceManager.GetObject("door_s_open", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_w_back {
			get {
				object obj = ResourceManager.GetObject("door_w_back", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_w_closed {
			get {
				object obj = ResourceManager.GetObject("door_w_closed", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_w_open {
			get {
				object obj = ResourceManager.GetObject("door_w_open", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_dwarf_east {
			get {
				object obj = ResourceManager.GetObject("hero_dwarf_east", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_dwarf_north {
			get {
				object obj = ResourceManager.GetObject("hero_dwarf_north", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_dwarf_south {
			get {
				object obj = ResourceManager.GetObject("hero_dwarf_south", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_dwarf_west {
			get {
				object obj = ResourceManager.GetObject("hero_dwarf_west", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_elf_east {
			get {
				object obj = ResourceManager.GetObject("hero_elf_east", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_elf_north {
			get {
				object obj = ResourceManager.GetObject("hero_elf_north", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_elf_south {
			get {
				object obj = ResourceManager.GetObject("hero_elf_south", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_elf_west {
			get {
				object obj = ResourceManager.GetObject("hero_elf_west", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_select_dwarf {
			get {
				object obj = ResourceManager.GetObject("hero_select_dwarf", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_select_elf {
			get {
				object obj = ResourceManager.GetObject("hero_select_elf", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_select_warrior {
			get {
				object obj = ResourceManager.GetObject("hero_select_warrior", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_select_wizard {
			get {
				object obj = ResourceManager.GetObject("hero_select_wizard", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_warrior_east {
			get {
				object obj = ResourceManager.GetObject("hero_warrior_east", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_warrior_north {
			get {
				object obj = ResourceManager.GetObject("hero_warrior_north", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_warrior_south {
			get {
				object obj = ResourceManager.GetObject("hero_warrior_south", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_warrior_west {
			get {
				object obj = ResourceManager.GetObject("hero_warrior_west", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_wizard_east {
			get {
				object obj = ResourceManager.GetObject("hero_wizard_east", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_wizard_north {
			get {
				object obj = ResourceManager.GetObject("hero_wizard_north", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_wizard_south {
			get {
				object obj = ResourceManager.GetObject("hero_wizard_south", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_wizard_west {
			get {
				object obj = ResourceManager.GetObject("hero_wizard_west", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap spell_affectAll {
			get {
				object obj = ResourceManager.GetObject("spell_affectAll", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap spell_affectAll_used {
			get {
				object obj = ResourceManager.GetObject("spell_affectAll_used", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap spell_explode {
			get {
				object obj = ResourceManager.GetObject("spell_explode", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap spell_explode_used {
			get {
				object obj = ResourceManager.GetObject("spell_explode_used", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap square_blue {
			get {
				object obj = ResourceManager.GetObject("square_blue", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap square_red {
			get {
				object obj = ResourceManager.GetObject("square_red", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tile_stairs {
			get {
				object obj = ResourceManager.GetObject("tile_stairs", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tile1 {
			get {
				object obj = ResourceManager.GetObject("tile1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tile2 {
			get {
				object obj = ResourceManager.GetObject("tile2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tile3 {
			get {
				object obj = ResourceManager.GetObject("tile3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tile4 {
			get {
				object obj = ResourceManager.GetObject("tile4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tile5 {
			get {
				object obj = ResourceManager.GetObject("tile5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tile6 {
			get {
				object obj = ResourceManager.GetObject("tile6", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tileWallE {
			get {
				object obj = ResourceManager.GetObject("tileWallE", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tileWallN {
			get {
				object obj = ResourceManager.GetObject("tileWallN", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tileWallS {
			get {
				object obj = ResourceManager.GetObject("tileWallS", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tileWallW {
			get {
				object obj = ResourceManager.GetObject("tileWallW", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap useDoor {
			get {
				object obj = ResourceManager.GetObject("useDoor", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
