//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungeons {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Images {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Images() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dungeons.Images", typeof(Images).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static System.Drawing.Bitmap arrow_leftturn_1 {
			get {
				object obj = ResourceManager.GetObject("arrow_leftturn_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_leftturn_2 {
			get {
				object obj = ResourceManager.GetObject("arrow_leftturn_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_leftturn_3 {
			get {
				object obj = ResourceManager.GetObject("arrow_leftturn_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_leftturn_4 {
			get {
				object obj = ResourceManager.GetObject("arrow_leftturn_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_north_1 {
			get {
				object obj = ResourceManager.GetObject("arrow_north_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_north_2 {
			get {
				object obj = ResourceManager.GetObject("arrow_north_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_north_3 {
			get {
				object obj = ResourceManager.GetObject("arrow_north_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_north_4 {
			get {
				object obj = ResourceManager.GetObject("arrow_north_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_rightturn_1 {
			get {
				object obj = ResourceManager.GetObject("arrow_rightturn_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_rightturn_2 {
			get {
				object obj = ResourceManager.GetObject("arrow_rightturn_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_rightturn_3 {
			get {
				object obj = ResourceManager.GetObject("arrow_rightturn_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_rightturn_4 {
			get {
				object obj = ResourceManager.GetObject("arrow_rightturn_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_scroll_east {
			get {
				object obj = ResourceManager.GetObject("arrow_scroll_east", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_scroll_north {
			get {
				object obj = ResourceManager.GetObject("arrow_scroll_north", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_scroll_reset {
			get {
				object obj = ResourceManager.GetObject("arrow_scroll_reset", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_scroll_south {
			get {
				object obj = ResourceManager.GetObject("arrow_scroll_south", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_scroll_west {
			get {
				object obj = ResourceManager.GetObject("arrow_scroll_west", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap baddie {
			get {
				object obj = ResourceManager.GetObject("baddie", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap closeCombat {
			get {
				object obj = ResourceManager.GetObject("closeCombat", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap dead_baddie {
			get {
				object obj = ResourceManager.GetObject("dead_baddie", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_e_back {
			get {
				object obj = ResourceManager.GetObject("door_e_back", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_e_closed {
			get {
				object obj = ResourceManager.GetObject("door_e_closed", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_e_open {
			get {
				object obj = ResourceManager.GetObject("door_e_open", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_n_back {
			get {
				object obj = ResourceManager.GetObject("door_n_back", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_n_closed {
			get {
				object obj = ResourceManager.GetObject("door_n_closed", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_n_open {
			get {
				object obj = ResourceManager.GetObject("door_n_open", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_s_back {
			get {
				object obj = ResourceManager.GetObject("door_s_back", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_s_closed {
			get {
				object obj = ResourceManager.GetObject("door_s_closed", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_s_open {
			get {
				object obj = ResourceManager.GetObject("door_s_open", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_w_back {
			get {
				object obj = ResourceManager.GetObject("door_w_back", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_w_closed {
			get {
				object obj = ResourceManager.GetObject("door_w_closed", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap door_w_open {
			get {
				object obj = ResourceManager.GetObject("door_w_open", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_east_1 {
			get {
				object obj = ResourceManager.GetObject("hero_east_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_east_2 {
			get {
				object obj = ResourceManager.GetObject("hero_east_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_east_3 {
			get {
				object obj = ResourceManager.GetObject("hero_east_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_east_4 {
			get {
				object obj = ResourceManager.GetObject("hero_east_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_north_1 {
			get {
				object obj = ResourceManager.GetObject("hero_north_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_north_2 {
			get {
				object obj = ResourceManager.GetObject("hero_north_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_north_3 {
			get {
				object obj = ResourceManager.GetObject("hero_north_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_north_4 {
			get {
				object obj = ResourceManager.GetObject("hero_north_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_select_1 {
			get {
				object obj = ResourceManager.GetObject("hero_select_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_select_2 {
			get {
				object obj = ResourceManager.GetObject("hero_select_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_select_3 {
			get {
				object obj = ResourceManager.GetObject("hero_select_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_select_4 {
			get {
				object obj = ResourceManager.GetObject("hero_select_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_south_1 {
			get {
				object obj = ResourceManager.GetObject("hero_south_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_south_2 {
			get {
				object obj = ResourceManager.GetObject("hero_south_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_south_3 {
			get {
				object obj = ResourceManager.GetObject("hero_south_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_south_4 {
			get {
				object obj = ResourceManager.GetObject("hero_south_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_west_1 {
			get {
				object obj = ResourceManager.GetObject("hero_west_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_west_2 {
			get {
				object obj = ResourceManager.GetObject("hero_west_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_west_3 {
			get {
				object obj = ResourceManager.GetObject("hero_west_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_west_4 {
			get {
				object obj = ResourceManager.GetObject("hero_west_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap rangedCombat {
			get {
				object obj = ResourceManager.GetObject("rangedCombat", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tile1 {
			get {
				object obj = ResourceManager.GetObject("tile1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tile2 {
			get {
				object obj = ResourceManager.GetObject("tile2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tile3 {
			get {
				object obj = ResourceManager.GetObject("tile3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tile4 {
			get {
				object obj = ResourceManager.GetObject("tile4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tile5 {
			get {
				object obj = ResourceManager.GetObject("tile5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tile6 {
			get {
				object obj = ResourceManager.GetObject("tile6", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tileWallE {
			get {
				object obj = ResourceManager.GetObject("tileWallE", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tileWallN {
			get {
				object obj = ResourceManager.GetObject("tileWallN", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tileWallS {
			get {
				object obj = ResourceManager.GetObject("tileWallS", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap tileWallW {
			get {
				object obj = ResourceManager.GetObject("tileWallW", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap useDoor {
			get {
				object obj = ResourceManager.GetObject("useDoor", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
